from unicodedata import category
from app.models import db, Product


# Adds a demo user, you can add other users here if you want
def seed_products():
    GAMEOFTHRONES = Product(
        name='Game of Thrones', description='Winter is coming. Such is the stern motto of House Stark, the northernmost of the fiefdoms that owe allegiance to King Robert Baratheon in far-off Kings Landing. There Eddard Stark of Winterfell rules in Roberts name. There his family dwells in peace and comfort: his proud wife, Catelyn; his sons Robb, Brandon, and Rickon; his daughters Sansa and Arya; and his bastard son, Jon Snow. Far to the north, behind the towering Wall, lie savage Wildings and worse - unnatural things relegated to myth during the centuries-long summer, but proving all too real and all too deadly in the turning of the season. Yet a more immediate threat lurks to the south, where Jon Arryn, the Hand of the King, has died under mysterious circumstances. Now Robert is riding north to Winterfell, bringing his queen, the lovely but cold Cersei, his son, the cruel, vainglorious Prince Joffrey, and the queens brothers Jaime and Tyrion of the powerful and wealthy House Lannister - the first a swordsman without equal, the second a dwarf whose stunted stature belies a brilliant mind.', price='12.99', category='fantasy', author='George R.R. Martin', photourl='https://m.media-amazon.com/images/I/51rDpMtBm5L.jpg')
    THENAMEOFTHEWIND = Product(
        name='Name of the Wind', description='The Name of the Wind, also referred to as The Kingkiller Chronicle: Day One, is a heroic fantasy novel written by American author Patrick Rothfuss. It is the first book in the ongoing fantasy trilogy The Kingkiller Chronicle, followed by The Wise Mans Fear. It was published on March 27, 2007, by DAW Books.', price='9.89', category='fantasy', author='Patrick Rothfuss', photourl='https://images-na.ssl-images-amazon.com/images/I/91b8oNwaV1L.jpg')
    THELORDOFTHERINGS = Product(
        name='Lord of the Rings', description='Since it was first published in 1954, The Lord of the Rings has been a book people have treasured. Steeped in unrivaled magic and otherworldliness, Tolkien\'s sweeping fantasy and epic adventure has touched the hearts of young and old alike. More than 150 million copies of its many editions have been sold around the world, and occasional collectors’ editions become prized and valuable items of publishing. This one-volume, jacketed hardcover edition contains the complete text, fully corrected and reset, which is printed in red and black and features, for the very first time, thirty color illustrations, maps and sketches drawn by Tolkien himself as he composed this epic work. These include the pages from the Book of Mazarbul, marvelous facsimiles created by Tolkien to accompany the famous ‘Bridge of Khazad-dum’ chapter. Also appearing are two removable fold-out maps drawn by Christopher Tolkien revealing all the detail of Middle-earth. Sympathetically packaged to reflect the classic look of the first edition, this new edition of the bestselling hardback will prove irresistible to collectors and new fans alike.', price='10.99', category='fantasy', author='John Tolkien', photourl='https://images-na.ssl-images-amazon.com/images/I/71jLBXtWJWL.jpg')
    COLOROFMAGIC = Product(
        name='Color of Magic', description='The Colour of Magic & The Light Fantastic: This is how the Discworld began... In The Colour of Magic the failed wizard Rincewind burst upon the world and hasn\'t stopped running since. This was the book that started the phenomenally successful fantasy series. Here is the sapient pearwood Luggage, a mobile trunk which launders any clothes put in it and incidentally homicidally defends its owner. Here is Twoflower, an innocent tourist in a world of nightmares and fairy tales gone wrong. Here is Cohen the Barbarian, the world\'s oldest and greatest hero. Here is Death, not such a bad sort when you get to know him... They have adventures. It\'d take to long too explain. Just read it! First published in 1983, The Colour of Magic has been translated into thirty languages, and has sold over two million copies in Corgi editions alone. The Light Fantastic, published in 1986, follows closely behind, and of all the Discworld novels it is the only true sequel to an earlier work. This two-in-one volume was first published in 1999.', price='13.99', category='fantasy', author='Terry Pratchett', photourl='https://images-na.ssl-images-amazon.com/images/I/91u24IHWS8L.jpg')
    EIGHTYFOUR = Product(
        name='1984', description='“The Party told you to reject the evidence of your eyes and ears. It was their final, most essential command.” Winston Smith toes the Party line, rewriting history to satisfy the demands of the Ministry of Truth. With each lie he writes, Winston grows to hate the Party that seeks power for its own sake and persecutes those who dare to commit thoughtcrimes. But as he starts to think for himself, Winston can’t escape the fact that Big Brother is always watching...A startling and haunting novel, 1984 creates an imaginary world that is completely convincing from start to finish. No one can deny the novel’s hold on the imaginations of whole generations, or the power of its admonitions—a power that seems to grow, not lessen, with the passage of time.', price='14.99', category='sci-fi', author='George Orwell', photourl='https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg')
    FAHRENHEIT = Product(
        name='Fahrenheit 451', description='Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But when he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known.', price='8.29', category='sci-fi', author='Ray Bradbury', photourl='https://www.arts.gov/sites/default/files/Fahrenheit%20451%20Cover.jpg')
    BRAVENEWWORLD = Product(
        name='Brave New World', description='Aldous Huxley\'s profoundly important classic of world literature, Brave New World is a searching vision of an unequal, technologically-advanced future where humans are genetically bred, socially indoctrinated, and pharmaceutically anesthetized to passively uphold an authoritarian ruling order–all at the cost of our freedom, full humanity, and perhaps also our souls. “A genius [who] who spent his life decrying the onward march of the Machine” (The New Yorker), Huxley was a man of incomparable talents: equally an artist, a spiritual seeker, and one of history’s keenest observers of human nature and civilization. Brave New World, his masterpiece, has enthralled and terrified millions of readers, and retains its urgent relevance to this day as both a warning to be heeded as we head into tomorrow and as thought-provoking, satisfying work of literature. Written in the shadow of the rise of fascism during the 1930s, Brave New World likewise speaks to a 21st-century world dominated by mass-entertainment, technology, medicine and pharmaceuticals, the arts of persuasion, and the hidden influence of elites.', price='10.99', category='sci-fi', author='Aldous Huxley', photourl='https://images-na.ssl-images-amazon.com/images/I/81zE42gT3xL.jpg')
    DUNE = Product(
        name='Dune', description='Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, who would become the mysterious man known as Maud\'dib. He would avenge the traitorous plot against his noble family - and would bring to fruition humankind\'s most ancient and unattainable dream. A stunning blend of adventure and mysticism, environmentalism and politics, Dune won the first Nebula Award, shared the Hugo Award, and formed the basis of what is undoubtedly the grandest epic in science fiction.Frank Herbert\'s death in 1986 was a tragic loss, yet the astounding legacy of his visionary fiction will live forever.', price='10.99', category='sci-fi', author='Frank Herbert', photourl='https://images-na.ssl-images-amazon.com/images/I/81ym3QUd3KL.jpg')
    IMPERIAL = Product(
        name='The Imperial Radch Trilogy', description='Breq is a human now — but once she was a starship. Once she was an AI with a vast and ancient metal body and troops of ancillaries, barely animate bodies that all carried her consciousness. Poll judge Ann Leckie has created a massive yet intricate interstellar empire where twisty galactic intrigues and multiple clashing cultures form a brilliant backdrop for the story of a starship learning to be a human being. Your humble editor got a copy of Ancillary Justice when it came out and promptly forced her entire family to read it.', price='9.99', category='sci-fi', author='Ann Leckie', photourl='https://media.npr.org/assets/img/2021/08/12/91dqqtm4u5l_custom-5d35b7fd36fde5c0ba428c542eacddf8f1c86c10-s500-c85.webp')
    MOONSTONE = Product(
        name='Moonstone', description='The Moonstone by Wilkie Collins. Introduction and Notes by David Blair, Rutherford College, University of Kent The Moonstone, a priceless Indian diamond which had been brought to England as spoils of war, is given to Rachel Verrinder on her eighteenth birthday. That very night, the stone is stolen. Suspicion then falls on a hunchbacked housemaid, on Rachel\'s cousin Franklin Blake, on a troupe of mysterious Indian jugglers, and on Rachel herself. The phlegmatic Sergeant Cuff is called in, and with the help of Betteredge, the Robinson Crusoe-reading loquacious steward, the mystery of the missing stone is ingeniously solved.', price='5.99', category='mystery', author='Wilkie Collins', photourl='https://images-na.ssl-images-amazon.com/images/I/41sxrEkyqdL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg')
    SCARLET = Product(
        name='Scarlet', description='Arthur Conan Doyle’s first ‘Sherlock Homes’ novel introduces the talented detective Holmes to his loyal partner in investigation, Dr. John Watson. A Study in Scarlet is the first of four full length Sherlock Holmes novels written by Arthur Conan Doyle. The novel begins with a war-wounded Watson being introduced to Holmes by a common friend, when looking for a place to stay. Initially wary of Holmes’s eccentricities, Watson gradually starts appreciating Sherlock’s knowledge and exceptional abilities of logical deduction.', price='9.99', category='mystery', author='Marissa Meyer', photourl='https://www.publicbookshelf.com/images/AStudyInScarlet423x630.jpg')
    MURDER = Product(
        name='Murder on the Orient Express', description='“Just after midnight, the famous Orient Express is stopped in its tracks by a snowdrift. By morning, the millionaire Samuel Edward Ratchett lies dead in his compartment, stabbed a dozen times, his door locked from the inside. Without a shred of doubt, one of his fellow passengers is the murderer. Isolated by the storm, detective Hercule Poirot must find the killer among a dozen of the dead man’s enemies, before the murderer decides to strike again. “What more . . . can a mystery addict desire?” — New York Times', price='8.49', category='mystery', author='Agatha Christie', photourl='https://m.media-amazon.com/images/P/0062073494.01._SCLZZZZZZZ_SX500_.jpg')
    POISONED = Product(
        name='The Poisoned Chocolates Case', description='“Graham and Joan Bendix have apparently succeeded in making that eighth wonder of the modern world, a happy marriage. But into the middle of it drops a box of chocolates. Joan Bendix is killed by a poisoned box of liqueur chocolates that cannot have been intended for her. The police investigation reaches a dead end. Chief Inspector Moresby calls on Roger Sheringham and his Crimes Circle - six amateur but intrepid detectives - to consider the case. The evidence is laid before them and they take turns to offer a solution. Each is more convincing than the last, slowly filling in the pieces of the puzzle, until the dazzling conclusion.” — New York Times', price='32.50', category='mystery', author='Anthony Berkeley', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/51T5N0KOoJL._SX320_BO1,204,203,200_.jpg')
    DONQUIXOTE = Product(
        name='Don Quixote', description='“Don Quixote has become so entranced reading tales of chivalry that he decides to turn knight errant himself. In the company of his faithful squire, Sancho Panza, these exploits blossom in all sorts of wonderful ways. While Quixote\'s fancy often leads him astray—he tilts at windmills, imagining them to be giants—Sancho acquires cunning and a certain sagacity. Sane madman and wise fool, they roam the world together-and together they have haunted readers\' imaginations for nearly four hundred years. With its experimental form and literary playfulness, Don Quixote has been generally recognized as the first modern novel. This Penguin Classics edition, with its beautiful new cover design, includes John Rutherford\'s masterly translation, which does full justice to the energy and wit of Cervantes\'s prose, as well as a brilliant critical introduction by Roberto Gonzalez Echevarriá.', price='12.99', category='action', author='Miguel de Cervantes', photourl='https://m.media-amazon.com/images/P/0142437239.01._SCLZZZZZZZ_SX500_.jpg')
    THREEMUSKETEERS = Product(
        name='The Three Musketeers', description='First serialized between March and July of 1844, Alexandre Dumas’s “The Three Musketeers” is one of the author’s most famous works, the opening installment in the “d\'Artagnan Romances.” A timeless tale of adventure, romance, intrigue, and revenge, it is the captivating story of d’Artagnan, a young man of Gascony, who is determined to become a Musketeer of the Royal Guard. Through his wit and skill with a sword, he befriends the other Musketeers, Athos, Porthos, and Aramis. Together they must foil the nefarious plotting of Cardinal Richelieu against the King and Queen, despite his appearance as an ally. The Musketeers must also overcome the villainous machinations of Milady de Winter, whose lethal criminality threatens those in power and the love of d’Artagnan for Constance Bonacieux. Dumas’s classic story has enthralled readers with its fast-paced action, endearing characters, and romantic ideals ever since its original publication. The camaraderie of the Musketeers has been forever immortalized by their famous motto “one for all, all for one.” This edition is printed on premium acid-free paper and includes an introduction by J. Walker McSpadden.', price='14.99', category='action', author='Alexandre Dumas', photourl='https://m.media-amazon.com/images/P/1420953788.01._SCLZZZZZZZ_SX500_.jpg')
    TREASURE = Product(
        name='Treasure Island', description='“**Published by Cricket House Books ISBN 9781625009975** “Treasure Island” is an adventure novel by the Scottish author Robert Louis Stevenson, published in 1883. It has had significant influence on the common perception of pirates. The novel is also a coming-of-age story, as the young protagonist, Jim, faces moral lessons and navigates dangerous situations.', price='9.99', category='action', author='Robert Louis Stevenson', photourl='https://m.media-amazon.com/images/P/1625009976.01._SCLZZZZZZZ_SX500_.jpg')
    MOBYDICK = Product(
        name='Moby Dick', description='“A masterpiece of storytelling, this epic saga pits Ahab, a brooding and fantastical sea captain, against the great white whale that crippled him. In telling the tale of Ahab\'s passion for revenge and the fateful voyage that ensued, Melville produced far more than the narrative of a hair-raising journey; Moby-Dick is a tale for the ages that sounds the deepest depths of the human soul.Interspersed with graphic sketches of life aboard a whaling vessel, and a wealth of information on whales and 19th-century whaling, Melville\'s greatest work presents an imaginative and thrilling picture of life at sea, as well as a portrait of heroic determination. The author\'s keen powers of observation and firsthand knowledge of shipboard life (he served aboard a whaler himself) were key ingredients in crafting a maritime story that dramatically examines the conflict between man and nature. "A valuable addition to the literature of the day," said American journalist Horace Greeley on the publication of Moby-Dick in 1851 — a classic piece of understatement about a literary classic now considered by many as "the great American novel." Read and pondered by generations, the novel remains an unsurpassed account of the ultimate human struggle against the indifference of nature and the awful power of fate. Much of Moby Dick was inspired by the 1821 work Narratives of the Wreck of the Whale-Ship Essex, which in turn inspired the 2015 movie In the Heart of the Sea, directed by Ron Howard and starring Chris Hemsworth.', price='5.99', category='action', author='Herman Melville', photourl='https://m.media-amazon.com/images/P/0486432157.01._SCLZZZZZZZ_SX500_.jpg')
    ELONMUSK = Product(
        name='Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future', description='New York Times and International Bestseller Named One of the Best Books of the Year by The Wall Street Journal, NPR, Audible and Amazon More than 2 million copies sold In the spirit of Steve Jobs and Moneyball, Elon Musk is both an illuminating and authorized look at the extraordinary life of one of Silicon Valley\'s most exciting, unpredictable, and ambitious entrepreneurs--a real-life Tony Stark--and a fascinating exploration of the renewal of American invention and its new "makers." Elon Musk spotlights the technology and vision of Elon Musk, the renowned entrepreneur and innovator behind SpaceX, Tesla, and SolarCity, who sold one of his Internet companies, PayPal, for $1.5 billion. Ashlee Vance captures the full spectacle and arc of the genius\'s life and work, from his tumultuous upbringing in South Africa and flight to the United States to his dramatic technical innovations and entrepreneurial pursuits. Vance uses Musk\'s story to explore one of the pressing questions of our age: can the nation of inventors and creators who led the modern world for a century still compete in an age of fierce global competition? He argues that Musk--one of the most unusual and striking figures in American business history--is a contemporary, visionary amalgam of legendary inventors and industrialists including Thomas Edison, Henry Ford, Howard Hughes, and Steve Jobs. More than any other entrepreneur today, Musk has dedicated his energies and his own vast fortune to inventing a future that is as rich and far-reaching as the visionaries of the golden age of science-fiction fantasy. Thorough and insightful, Elon Musk brings to life a technology industry that is rapidly and dramatically changing by examining the life of one of its most powerful and influential titans.', price='13.39', category='biography', author='Ashley Vance', photourl='https://m.media-amazon.com/images/P/006230125X.01._SCLZZZZZZZ_SX500_.jpg')
    STEVEJOBS = Product(
        name='Steve Jobs', description='“Based on more than 40 interviews with Jobs conducted over two years - as well as interviews with more than a hundred family members, friends, adversaries, competitors, and colleagues - Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies, music, phones, tablet computing, and digital publishing. At a time when America is seeking ways to sustain its innovative edge, and when societies around the world are trying to build digital-age economies, Jobs stands as the ultimate icon of inventiveness and applied imagination. He knew that the best way to create value in the 21st century was to connect creativity with technology. He built a company where leaps of the imagination were combined with remarkable feats of engineering. Although Jobs cooperated with this book, he asked for no control over what was written. He put nothing off-limits. He encouraged the people he knew to speak honestly. And Jobs speaks candidly, sometimes brutally so, about the people he worked with and competed against. His friends, foes, and colleagues provide an unvarnished view of the passions, perfectionism, obsessions, artistry, devilry, and compulsion for control that shaped his approach to business and the innovative products that resulted. Driven by demons, Jobs could drive those around him to fury and despair. But his personality and products were interrelated, just as Apple\'s hardware and software tended to be, as if part of an integrated system. His tale is instructive and cautionary, filled with lessons about innovation, character, leadership, and values.', price='15.50', category='biogrphy', author='Walter Isaacson', photourl='https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51S2iJN3DYL.jpg')
    EINSTEIN = Product(
        name='Einstein: His Life and Universe', description='How did Einstein\'s mind work? What made him a genius? Isaacson\'s biography shows how his scientific imagination sprang from the rebellious nature of his personality. His fascinating story is a testament to the connection between creativity and freedom. Based on the newly released personal letters of Albert Einstein, Walter Isaacson explores how an imaginative, impertinent patent clerk, a struggling father in a difficult marriage who couldn\'t get a teaching job or a doctorate, became the mind reader of the creator of the cosmos, the locksmith of the mysteries of the atom and the universe. His success came from questioning conventional wisdom and marveling at mysteries that struck others as mundane. This led him to embrace a morality and politics based on respect for free minds, free spirits, and free individuals. These traits are just as vital for this new century of globalization, in which our success will depend on our creativity, as they were for the beginning of the last century, when Einstein helped usher in the modern age.', price='12.46', category='biography', author='Walter Isaacson', photourl='https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51VEeZWAo-L.jpg')
    EDISON = Product(
        name='Thomas Edison: The One Who Changed The World', description='There are a lot more to the story than just the light bulb, and there is a lot more to the invention of the light bulb than just Thomas Edison. One thing is for sure that he is still remembered as one of the greatest inventors of all time, and perhaps the greatest that America has ever produced. In truth, Edison was a man who invented a lot of things while bringing about incredible advancements in many other things. With the stock ticker, the telegraph, the light bulb, and motion picture, he may not have invented them, but he improved on them beyond any recognition. They would not be the technologies they were today without Edison’s great mind working on them.', price='10.99', category='biography', author='THE HISTORY HOUR', photourl='https://m.media-amazon.com/images/P/171816095X.01._SCLZZZZZZZ_SX500_.jpg')
    DOAWK = Product(
        name='Diary of a Wimpy Kid', description='It’s a new school year, and Greg Heffley finds himself thrust into middle school, where undersized weaklings share the hallways with kids who are taller, meaner, and already shaving. The hazards of growing up before you’re ready are uniquely revealed through words and drawings as Greg records them in his diary. In book one of this debut series, Greg is happy to have Rowley, his sidekick, along for the ride. But when Rowley’s star starts to rise, Greg tries to use his best friend’s newfound popularity to his own advantage, kicking off a chain of events that will test their friendship in hilarious fashion. Author/illustrator Jeff Kinney recalls the growing pains of school life and introduces a new kind of hero who epitomizes the challenges of being a kid. As Greg says in his diary, “Just don’t expect me to be all ‘Dear Diary’ this and ‘Dear Diary’ that.” Luckily for us, what Greg Heffley says he won’t do and what he actually does are two very different things. Since its launch in May 2004 on Funbrain.com, the Web version of Diary of a Wimpy Kid has been viewed by 20 million unique online readers. This year, it is averaging 70,000 readers a day. F&P level: T', price='9.48', category='childrens', author='Jeff Kinney', photourl='https://m.media-amazon.com/images/P/0810993139.01._SCLZZZZZZZ_SX500_.jpg')
    TREEHOUSE = Product(
        name='Magic Tree House: Pirates Past Noon', description='The #1 bestselling chapter book series of all time celebrates 25 years with new covers and a new, easy-to-use numbering system! It\'s a treasure trove of trouble! Jack and Annie are in for a high-seas adventure when the Magic Tree House whisks them back to the days of deserted islands, secret maps—and ruthless pirates! Will they discover a buried treasure? Or will they be forced to walk the plank?', price='3.83', category='childrens', author='Mary Pope Osbourne', photourl='https://m.media-amazon.com/images/P/0679824251.01._SCLZZZZZZZ_SX500_.jpg')
    CHARLOTTE = Product(
        name='Charlotte\'s Web', description='Some Pig. Humble. Radiant. These are the words in Charlotte\'s Web, high up in Zuckerman\'s barn. Charlotte\'s spiderweb tells of her feelings for a little pig named Wilbur, who simply wants a friend. They also express the love of a girl named Fern, who saved Wilbur\'s life when he was born the runt of his litter. E. B. White\'s Newbery Honor Book is a tender novel of friendship, love, life, and death that will continue to be enjoyed by generations to come. It contains illustrations by Garth Williams, the acclaimed illustrator of E. B. White\'s Stuart Little and Laura Ingalls Wilder\'s Little House series, among many other books. Whether enjoyed in the classroom or for homeschooling or independent reading, Charlotte\'s Web is a proven favorite.', price='5.47', category='childrens', author='E.B. White', photourl='https://m.media-amazon.com/images/P/0064400557.01._SCLZZZZZZZ_SX500_.jpg')
    HARRYPOTTER = Product(
        name='Harry Potter and the Sorcerer\'s Stone', description='Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry\'s eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!  — New York Times', price='9.99', category='childrens', author='J.K. Rowling', photourl='https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51Ppi-8kISL.jpg')
    THEWOK = Product(
        name='The Wok: Recipes and Techniques', description='“J. Kenji López-Alt’s debut cookbook, The Food Lab, revolutionized home cooking, selling more than half a million copies with its science-based approach to everyday foods. And for fast, fresh cooking for his family, there’s one pan López-Alt reaches for more than any other: the wok. Whether stir-frying, deep frying, steaming, simmering, or braising, the wok is the most versatile pan in the kitchen. Once you master the basics―the mechanics of a stir-fry, and how to get smoky wok hei at home―you’re ready to cook home-style and restaurant-style dishes from across Asia and the United States, including Kung Pao Chicken, Pad Thai, and San Francisco–Style Garlic Noodles. López-Alt also breaks down the science behind beloved Beef Chow Fun, fried rice, dumplings, tempura vegetables or seafood, and dashi-simmered dishes. Featuring more than 200 recipes―including simple no-cook sides―explanations of knife skills and how to stock a pantry, and more than 1,000 color photographs, The Wok provides endless ideas for brightening up dinner.', price='29.69', category='cookbooks', author='J. Kenji López-Alt ', photourl='https://m.media-amazon.com/images/P/0393541215.01._SCLZZZZZZZ_SX500_.jpg')
    HOMEFOOD = Product(
        name='Home Food: 100 Recipes to Comfort and Connect', description='In her most personal book yet, Olia Hercules distills a lifetime of kitchen curiosity into her 100 most loved recipes. She draws on her broad influences: her childhood in Eastern Europe; her years in Cyprus and Italy; her simple, plant-centric family meals at home in London; and the special festive recipes she has gleaned along the way. All these seemingly diverse recipes are centered in comfort and connection. These are recipes that have been hand written, handed down, and shared among friends: “They are nostalgic like the potatoes of my childhood, they share trade secrets like Bisque-style red mullet pasta, they interweave every day like Joe’s beet, feta, and potatoes, and they make everything ok like Life-giving rhubarb cake. The foods we choose to cook time and again are part of what makes us, and when we share those recipes, we give a little of ourselves.” In this book Olia gives us her food story through her very favorite recipes.', price='31.50', category='cookbooks', author='Olia Hercules', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/515umZ9nRbL._SX391_BO1,204,203,200_.jpg')
    HALFBAKED = Product(
        name='Half Baked Harvest Every Day', description='The millions of fans of the Half Baked Harvest blog and bestselling books have fallen in love with Tieghan Gerard’s recipes for their wholesome decadence, unfussy approach, and smart twists on comforting favorites. Written and photographed in the stunning mountains of Colorado, inspired by her big, unique family, and focused on what you’ll want to eat day-in-day-out, Half Baked Harvest Every Day delivers more than 120 all-new recipes that will feed your body and soul. For Tieghan, feel-good food isn’t about restrictive eating. It’s about enjoying real food with lots of flavor, and the satisfaction of sharing it with those you love. Finding balance is about giving your body and your cravings what they need . . . whether that’s a light, vegetable-packed dish or a big ole plate of something comforting. In this collection, there are plenty of plant-forward favorites, like Chipotle Cheddar Corn Chowder and Spinach and Pesto–Stuffed Butternut Squash. Tieghan also shares flavor-packed family go-tos, like Pizza Pasta with Pepperoni Bread Crumbs, Crispy Carnitas Taquitos, and Spicy Pretzel Chicken Fingers with Hot Honey. And to keep a smile on everyone’s face, you’ll find luscious desserts, like Chocolate Olive Oil Cake and a Lemon Tart with Vanilla Sugar, made with a focus on wholesome, minimally processed ingredients. Whether it’s breakfast, lunch, snack time, dinner, or dessert . . . this book has tried-and-true recipes that will make you feel good about sharing them at your table.', price='18.49', category='cookbooks', author='Tieghan Gerard', photourl='https://assets.wsimgs.com/wsimgs/ab/images/dp/wcm/202221/0044/img87o.jpg')
    MASALA = Product(
        name='Masala: Recipes from India, the Land of Spices', description='Award-winning chef Anita Jaisinghani of Pondicheri restaurant in Houston, Texas, shows just how easy, delicious, and healthy Indian food can be in this stunning and accessible debut cookbook. Born and raised in Gujarat, India, Anita’s approach to cooking is simple: Following the tenets of ancient Ayurveda, food is seasonal, texture and color are celebrated, and spices are used to enhance, not overwhelm. As the star of Indian cuisine, spices are used from morning to night, in simple infusions, such as cinnamon water for a warming start the day, while cilantro and mint add a cooling balance to a fiery grilled corn salad, and cardamom lends an aromatic sweetness to mango rice pudding. Masala will teach you to think like an Indian chef, revealing the wisdom and techniques to cooking with fresh whole spices: identifying warming versus cooling, what order they should be used, how to temper in hot oil, and much more. Drawing inspiration from every corner of India, these recipes include fermented dosas, sweet and savory chutneys, fragrant chicken, fish, and pork curries, samosas, pakoras, and naans, and pay homage to one of the oldest and most diverse cuisines on the planet. Expect to be wowed with new flavors and combinations, such as Saffron Citrus Pilaf, Coconut Lassi, Jackfruit Masala, Vindaloo Ribs, Avocado Mushroom Chilla, and Smoked Eggplant Raita.', price='33.12', category='cookbooks', author='Anita Jaisinghani', photourl='https://images-na.ssl-images-amazon.com/images/I/A1xK8xq8+-L.jpg')
    HAUNTINGHILL = Product(
        name='The Haunting of Hill House', description='First published in 1959, Shirley Jackson\'s The Haunting of Hill House has been hailed as a perfect work of unnerving terror. It is the story of four seekers who arrive at a notoriously unfriendly pile called Hill House: Dr. Montague, an occult scholar looking for solid evidence of a "haunting"; Theodora, his lighthearted assistant; Eleanor, a friendless, fragile young woman well acquainted with poltergeists; and Luke, the future heir of Hill House. At first, their stay seems destined to be merely a spooky encounter with inexplicable phenomena. But Hill House is gathering its powers—and soon it will choose one of them to make its own. For more than seventy years, Penguin has been the leading publisher of classic literature in the English-speaking world. With more than 1,700 titles, Penguin Classics represents a global bookshelf of the best works throughout history and across genres and disciplines. Readers trust the series to provide authoritative texts enhanced by introductions and notes by distinguished scholars and contemporary authors, as well as up-to-date translations by award-winning translators.', price='12.49', category='horror', author='Shirley Jackson', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/91sU9Ot1YML.jpg')
    IT = Product(
        name='IT', description='Stephen King’s terrifying, classic number one New York Times best seller, “a landmark in American literature” (Chicago Sun-Times) - about seven adults who return to their hometown to confront a nightmare they had first stumbled on as teenagers…an evil without a name: It. Welcome to Derry, Maine. It’s a small city, a place as hauntingly familiar as your own hometown. Only in Derry the haunting is real. They were seven teenagers when they first stumbled upon the horror. Now they are grown-up men and women who have gone out into the big world to gain success and happiness. But the promise they made 28 years ago calls them reunite in the same place where, as teenagers, they battled an evil creature that preyed on the city’s children. Now, children are being murdered again, and their repressed memories of that terrifying summer return as they prepare to once again battle the monster lurking in Derry’s sewers. Readers of Stephen King know that Derry, Maine, is a place with a deep, dark hold on the author. It reappears in many of his books, including Bag of Bones, Hearts in Atlantis, and 11/22/63. But it all starts with It.', price='15.97', category='horror', author='Stephen King', photourl='https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/41xThcH7SLL.jpg')
    EXORCIST = Product(
        name='Exorcist', description='The Exorcist is a 1971 horror novel by American writer William Peter Blatty. The book details the demonic possession of eleven-year-old Regan MacNeil, the daughter of a famous actress, and the two priests who attempt to exorcise the demon.', price='14.93', category='horror', author='William Peter Blatty ', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/41F2dFP5wLL._SX324_BO1,204,203,200_.jpg')
    LEAVES = Product(
        name='House of Leaves', description='Years ago, when House of Leaves was first being passed around, it was nothing more than a badly bundled heap of paper, parts of which would occasionally surface on the Internet. No one could have anticipated the small but devoted following this terrifying story would soon command. Starting with an odd assortment of marginalized youth -- musicians, tattoo artists, programmers, strippers, environmentalists, and adrenaline junkies -- the book eventually made its way into the hands of older generations, who not only found themselves in those strangely arranged pages but also discovered a way back into the lives of their estranged children. Now this astonishing novel is made available in book form, complete with the original colored words, vertical footnotes, and second and third appendices. The story remains unchanged, focusing on a young family that moves into a small home on Ash Tree Lane where they discover something is terribly wrong: their house is bigger on the inside than it is on the outside. Of course, neither Pulitzer Prize-winning photojournalist Will Navidson nor his companion Karen Green was prepared to face the consequences of that impossibility, until the day their two little children wandered off and their voices eerily began to return another story -- of creature darkness, of an ever-growing abyss behind a closet door, and of that unholy growl which soon enough would tear through their walls and consume all their dreams.', price='21.49', category='horror', author='Mark Z. Danielewski', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/810pcXb+l3L.jpg')
    SEVENTEENSEVENTYSIX = Product(
        name='1776', description='In this stirring audiobook, David McCullough tells the intensely human story of those who marched with General George Washington in the year of the Declaration of Independence, when the whole American cause was riding on their success, without which all hope for independence would have been dashed and the noble ideals of the Declaration would have amounted to little more than words on paper. Based on extensive research in both American and British archives, 1776 is the story of Americans in the ranks, men of every shape, size, and color, farmers, schoolteachers, shoemakers, no-accounts, and mere boys turned soldiers. And it is the story of the British commander, William Howe, and his highly disciplined redcoats, who looked on their rebel foes with contempt and fought with a valor too little known. But it is the American commander-in-chief who stands foremost: Washington, who had never before led an army in battle. The darkest hours of that tumultuous year were as dark as any Americans have known. Especially in our own tumultuous time, 1776 is powerful testimony to how much is owed to a rare few in that brave founding epoch, and what a miracle it was that things turned out as they did. Written as a companion work to his celebrated biography of John Adams, David McCullough\'s 1776 is another landmark in the literature of American history.', price='10.38', category='history', author='David Mccullough', photourl='https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51tAmoigKnL.jpg')
    CRUSADES = Product(
        name='The Crusades', description='The Crusades is an authoritative, accessible single-volume history of the brutal struggle for the Holy Land in the Middle Ages. Thomas Asbridge - a renowned historian who writes with "maximum vividness" (Joan Acocella, The New Yorker) - covers the years 1095 to 1291 in this big, ambitious, listenable account of one of the most fascinating periods in history. From Richard the Lionheart to the mighty Saladin, from the emperors of Byzantium to the Knights Templar, Asbridge\'s book is a magnificent epic of holy war between the Christian and Islamic worlds, full of adventure, intrigue, and sweeping grandeur.', price='14.99', category='history', author='Thomas Asbridge', photourl='https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51o854cKoVL.jpg')
    GUNSGERMSSTEEL = Product(
        name='Guns, Germs, and Steel: The Fates of Human Societies', description='Why did Eurasians conquer, displace, or decimate Native Americans, Australians, and Africans, instead of the reverse? In this “artful, informative, and delightful” (William H. McNeill, New York Review of Books) book, a classic of our time, evolutionary biologist Jared Diamond dismantles racist theories of human history by revealing the environmental factors actually responsible for its broadest patterns. The story begins 13,000 years ago, when Stone Age hunter-gatherers constituted the entire human population. Around that time, the developmental paths of human societies on different continents began to diverge greatly. Early domestication of wild plants and animals in the Fertile Crescent, China, Mesoamerica, the Andes, and other areas gave peoples of those regions a head start at a new way of life. But the localized origins of farming and herding proved to be only part of the explanation for their differing fates. The unequal rates at which food production spread from those initial centers were influenced by other features of climate and geography, including the disparate sizes, locations, and even shapes of the continents. Only societies that moved away from the hunter-gatherer stage went on to develop writing, technology, government, and organized religions as well as deadly germs and potent weapons of war. It was those societies, adventuring on sea and land, that invaded others, decimating native inhabitants through slaughter and the spread of disease. A major landmark in our understanding of human societies, Guns, Germs, and Steel chronicles the way in which the modern world, and its inequalities, came to be. ', price='14.41', category='history', author='Jared Diamond', photourl='https://m.media-amazon.com/images/I/51-KH9CL1SL.jpg')
    EUROPE = Product(
        name='A Short History of Europe: From Pericles to Putin', description='In just a few hundred years, a modest peninsula off the northwest corner of Asia has seen the rise and fall of several empires; served as the crucible for scientific dynamism, cultural innovation, and economic revolution; and witnessed cataclysms and bloodshed that have almost destroyed it several times over. This is Europe: a continent whose identity emerged not so much by virtue of geographic or ethnic continuity, but by a long and storied struggle for power. Studded with infamous figures--from Caesar to Charlemagne and Machiavelli to Marx--Simon Jenkins\'s history of Europe travels briskly from the Roman Empire, the Dark Ages, and the Reformation through the French Revolution, the World Wars, and the fall of the USSR. What emerges in this thrilling and expansive telling is a continent as defined by its continually clashing cultural identities and violent crises as it is by its tireless drive for a society based on the consent of the governed -- which holds true right up to the present day. ', price='35.00', category='history', author='Simon Jenkins', photourl='https://images-na.ssl-images-amazon.com/images/I/517ZdFvBIwL.jpg')
    MOCKINGBIRD = Product(
        name='To Kill a Mockingbird', description='One of the most cherished stories of all time, To Kill a Mockingbird has been translated into more than forty languages, sold more than forty million copies worldwide, served as the basis for an enormously popular motion picture, and was voted one of the best novels of the twentieth century by librarians across the country. A gripping, heart-wrenching, and wholly remarkable tale of coming-of-age in a South poisoned by virulent prejudice, it views a world of great beauty and savage inequities through the eyes of a young girl, as her father—a crusading local lawyer—risks everything to defend a black man unjustly accused of a terrible crime.', price='7.19', category='literary-fiction', author='Harper Lee', photourl='https://cdn.britannica.com/21/182021-050-666DB6B1/book-cover-To-Kill-a-Mockingbird-many-1961.jpg')
    GATSBY = Product(
        name='The Great Gatsby', description='The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, the novel depicts narrator Nick Carraway\'s interactions with mysterious millionaire Jay Gatsby and Gatsby\'s obsession to reunite with his former lover, Daisy Buchanan. A youthful romance Fitzgerald had with socialite Ginevra King, and the riotous parties he attended on Long Island\'s North Shore in 1922 inspired the novel. Following a move to the French Riviera, he completed a rough draft in 1924. He submitted the draft to editor Maxwell Perkins, who persuaded Fitzgerald to revise the work over the following winter. After his revisions, Fitzgerald was satisfied with the text, but remained ambivalent about the book\'s title and considered several alternatives. The final title he desired was Under the Red, White, and Blue. Painter Francis Cugat\'s final cover design impressed Fitzgerald who incorporated a visual element from the art into the novel. Gatsby continues to attract popular and scholarly attention. The novel was most recently adapted to film in 2013 by director Baz Luhrmann, while contemporary scholars emphasize the novel\'s treatment of social class, inherited wealth compared to those who are self-made, race, environmentalism, and its cynical attitude towards the American dream. The Great Gatsby is widely considered to be a literary masterpiece and a contender for the title of the Great American Novel. ', price='4.56', category='literary-fiction', author='F. Scott Fitzgerald', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/61z0MrB6qOS.jpg')
    CATCHER = Product(
        name='The Catcher in the Rye', description='Anyone who has read J.D. Salinger\'s New Yorker stories--particularly A Perfect Day for Bananafish, Uncle Wiggily in Connecticut, The Laughing Man, and For Esme With Love and Squalor--will not be surprised by the fact that his first novel is full of children. The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days. The boy himself is at once too simple and too complex for us to make any final comment about him or his story. Perhaps the safest thing we can say about Holden is that he was born in the world not just strongly attracted to beauty but, almost, hopelessly impaled on it. There are many voices in this novel: children\'s voices, adult voices, underground voices-but Holden\'s voice is the most eloquent of all. Transcending his own vernacular, yet remaining marvelously faithful to it, he issues a perfectly articulated cry of mixed pain and pleasure. However, like most lovers and clowns and poets of the higher orders, he keeps most of the pain to, and for, himself. The pleasure he gives away, or sets aside, with all his heart. It is there for the reader who can handle it to keep. ', price='14.39', category='literary-fiction', author='J. D. Salinger', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/71nXPGovoTL.jpg')
    ANIMALFARM = Product(
        name='Animal Farm: 75th Anniversary Edition', description='A farm is taken over by its overworked, mistreated animals. With flaming idealism and stirring slogans, they set out to create a paradise of progress, justice, and equality. Thus the stage is set for one of the most telling satiric fables ever penned—a razor-edged fairy tale for grown-ups that records the evolution from revolution against tyranny to a totalitarianism just as terrible. When Animal Farm was first published, Stalinist Russia was seen as its target. Today it is devastatingly clear that wherever and whenever freedom is attacked, under whatever banner, the cutting clarity and savage comedy of George Orwell’s masterpiece have a meaning and message still ferociously fresh. ', price='7.48', category='literary-fiction', author='George Orwell', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/71wdbkiRokL.jpg')
    ONEPIECE = Product(
        name='One Piece, Vol. 1: Romance Dawn', description='As a child, Monkey D. Luffy dreamed of becoming King of the Pirates. But his life changed when he accidentally gained the power to stretch like rubber…at the cost of never being able to swim again! Years, later, Luffy sets off in search of the “One Piece,” said to be the greatest treasure in the world... As a child, Monkey D. Luffy was inspired to become a pirate by listening to the tales of the buccaneer "Red-Haired" Shanks. But his life changed when Luffy accidentally ate the Gum-Gum Devil Fruit and gained the power to stretch like rubber...at the cost of never being able to swim again! Years later, still vowing to become the king of the pirates, Luffy sets out on his adventure...one guy alone in a rowboat, in search of the legendary "One Piece," said to be the greatest treasure in the world... ', price='7.68', category='manga', author='Eiichiro Oda', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/91NxYvUNf6L.jpg')
    NARUTO = Product(
        name='Naruto, Vol. 1: Uzumaki Naruto', description='Naruto is a young shinobi with an incorrigible knack for mischief. He’s got a wild sense of humor, but Naruto is completely serious about his mission to be the world’s greatest ninja! Twelve years ago the Village Hidden in the Leaves was attacked by a fearsome threat. A nine-tailed fox spirit claimed the life of the village leader, the Hokage, and many others. Today, the village is at peace and a troublemaking kid named Naruto is struggling to graduate from Ninja Academy. His goal may be to become the next Hokage, but his true destiny will be much more complicated. The adventure begins now! ', price='9.99', category='manga', author='Masashi Kishimoto', photourl='http://prodimage.images-bn.com/pimages/9781569319000_p0_v1_s1200x630.jpg')
    DRAGONBALLZ = Product(
        name='Dragon Ball Z, Vol. 1', description='Five years have passed since the Tenka\'ichi Budōkai (Strongest Under the Heavens) fighting tournament, where Son Goku emerged as Earth\'s ultimate champion. Goku has since settled down with a wife and even has a son, Son Gohan. All seems peaceful, until one day when a mysterious visitor appears and reveals that Goku is actually an alien! The visitor, Raditz, claims that Goku is a Saiyan Warrior, a member of the most powerful race in the universe. When the ruthless Raditz threatens to destroy Goku\'s family and the entire human race, Goku races to stop him and finds an unlikely ally in Piccolo, his old archenemy... ', price='17.99', category='manga', author='Akira Toriyama', photourl='https://i5.walmartimages.com/asr/41f3cb2a-accc-4ca1-ab1e-7a47659cd5c6_1.a44981915c0b48a29dd878714ce78649.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF')
    DEATHNOTE = Product(
        name='Death Note, Vol. 1', description='Light Yagami is an ace student with great prospects--and he\'s bored out of his mind. But all that changes when he finds the Death Note, a notebook dropped by a rogue Shinigami death god. Any human whose name is written in the notebook dies, and now Light has vowed to use the power of the Death Note to rid the world of evil. But when criminals begin dropping dead, the authorities send the legendary detective L to track down the killer. With L hot on his heels, will Light lose sight of his noble goal...or his life? Light tests the boundaries of the Death Note\'s powers as L and the police begin to close in. Luckily Light\'s father is the head of the Japanese National Police Agency and leaves vital information about the case lying around the house. With access to his father\'s files, Light can keep one step ahead of the authorities. But who is the strange man following him, and how can Light guard against enemies whose names he doesn\'t know? ', price='9.99', category='manga', author='Tsugumi Ohba', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/51SkSDhUidL.jpg')
    MILKHONEY = Product(
        name='Milk and Honey', description='#1 New York Times bestseller milk and honey is a collection of poetry and prose about survival. About the experience of violence, abuse, love, loss, and femininity. The book is divided into four chapters, and each chapter serves a different purpose. Deals with a different pain. Heals a different heartache. milk and honey takes readers through a journey of the most bitter moments in life and finds sweetness in them because there is sweetness everywhere if you are just willing to look. ', price='7.38', category='poetry', author='Rupi Kaur', photourl='https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/71Eq55V2AvL._AC_UY436_FMwebp_QL65_.jpg')
    CHASESUN = Product(
        name='To Chase The Sun', description='To Chase the Sun is a collection of work that charts one poet’s journey from the darkness back into the light. This search for hope is reflected in his stages of healing from Chaos, to Order, and Beyond. "I find that I am in love with the night, perhaps it\'s nought but an ache for the sun." -- Craig Randall ', price='7.99', category='poetry', author='Craig Randall', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/51cQrEgl6WL.jpg')
    HEALING = Product(
        name='Healing Is a Gift: Poems for Those Who Need to Grow', description='Healing Is a Gift is an empowering poetry collection that explores the profound themes of healing, letting go, changing your old self, loving and appreciating yourself more, growing with hope, and rising again like a bold, beautiful soul. This uplifting book brings you a powerful and positive message: when you overcome adversities, let go of your past, mend your heart’s wounds, and move forward with your life, you actually give the greatest gifts to yourself. Choose Healing Is a Gift and start your inward journey towards healing, love, self-esteem, growth, hope, and happiness. ', price='12.89', category='poetry', author='Alexandra Vasiliu', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/51fujkVCwnL.jpg')
    SUNFLOWERS = Product(
        name='how sunflowers bloom under moonlight', description='there are two ways you can read this book. whenever your heart tells you to, pick up this book, flip to a random page and let the universe give you the poem you need most. do not read in order. do not read in one go. do not read unless something inside of you is begging to read it like a story, front to back, with as few breaks as possible. visualise each poem as a different chapter in a love story, because you should know that it absolutely is. read it like you have written it, you are alone, you are in love, you are heartbroken. read it and let yourself feel it; all of it 20 years in the making, ‘how sunflowers bloom under moonlight’ is the story of isabella’s journey through love, heartbreak and everything in between. her debut poetry book is split into three sections that flow into one another, letting every person who has had their heart broken, see the thoughts in their head finally written on paper. isabella’s book was created to, in her own words, ‘give people the comfort of knowing they are not alone in their emotions’. from relationships, to body image, to mental health, ‘how sunflowers bloom under moonlight’ has the sole purpose of making you giggle, cry, smile, reflect and cry a little bit more. so, keep a box of tissues close, find a quite place to read and allow yourself to feel absolutely everything. ', price='14.21', category='poetry', author='isabella dorta', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/61JIHY+44TL.jpg')
    WHATSHEFOUND = Product(
        name='What She Found', description='“Detective Tracy Crosswhite has agreed to look into the disappearance of investigative reporter Lisa Childress. Solving the cold case is an obsession for Lisa’s daughter, Anita. So is clearing the name of her father, a prime suspect who became a pariah. After twenty-five years, all Anita wants is the truth―no matter where it leads. For Tracy, that means reopening the potentially explosive investigations Lisa was following on the dark night she vanished: an exposé of likely mayoral graft; the shocking rumors of a reserved city councilman’s criminal sex life; a drug task force scandal compromising the Seattle PD; and an elusive serial killer who disappeared just as mysteriously as Lisa. As all the pieces come together, it becomes clear that Tracy is in the midst of a case that will push her loyalties and her resilience to the limit. What she uncovers will come with a greater price than anyone feared.', price='11.99', category='mystery', author='Robert Dugoni', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/91iSuEJGAyL.jpg')
    REMINDERS = Product(
        name='Reminders of Him: A Novel', description='“After serving five years in prison for a tragic mistake, Kenna Rowan returns to the town where it all went wrong, hoping to reunite with her four-year-old daughter. But the bridges Kenna burned are proving impossible to rebuild. Everyone in her daughter’s life is determined to shut Kenna out, no matter how hard she works to prove herself. The only person who hasn’t closed the door on her completely is Ledger Ward, a local bar owner and one of the few remaining links to Kenna’s daughter. But if anyone were to discover how Ledger is slowly becoming an important part of Kenna’s life, both would risk losing the trust of everyone important to them. The two form a connection despite the pressure surrounding them, but as their romance grows, so does the risk. Kenna must find a way to absolve the mistakes of her past in order to build a future out of hope and healing.', price='9.57', category='literary-fiction', author='Colleen Hoover', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/617uZq23IPL.jpg')
    BEYOND = Product(
        name='Beyond the Moonlit Sea: A Novel', description='“Olivia Hamilton is married to the love of her life, Dean, a charismatic pilot who flies private jets for the rich and famous. But when he vanishes over the Bermuda Triangle, Olivia’s idyllic existence unravels. After years of waiting, Olivia must eventually let go of the fragile hope that her beloved husband might still be alive. Melanie Brown is a particle physicist who spends late nights studying the Bermuda Triangle. But her research interests falter when her mother dies in a tragic accident. Struggling to reboot her life and career, Melanie begins a forbidden love affair with her therapist. When a shocking discovery shows Olivia’s and Melanie’s paths are intertwined, it casts Dean’s disappearance in a new light. The two women’s strange connection threatens to unlock secrets that will change everything Olivia thought she knew about her marriage, her husband, and most importantly, herself. Full of spellbinding twists and turns, Beyond the Moonlit Sea is a vivid, emotional novel about the stirring power of love lost and found―and the incredible strength of one woman who fights for happiness in the wake of tragedy.', price='13.46', category='literary-fiction', author='Julianne MacLean', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/81iwGQo8ogL.jpg')
    SUMMER = Product(
        name='Last Summer Boys: A Novel', description='“Summer 1968. When thirteen-year-old Jack Elliot overhears the barbershop men grousing, he devises a secret plan to keep his oldest brother, Pete, from the draft. If famous boys don’t go to war, he’ll make his brother their small town’s biggest celebrity. Jack gets unexpected help when his book-smart cousin Frankie arrives in their rural Pennsylvania town for the summer. Together, they convince Jack’s brothers to lead an expedition to find a fighter jet that crashed many winters ago―the perfect adventure to make Pete a hero. But with a greedy developer determined to flood their valley, a beautiful girl occupying his middle brother’s attentions, a wild motorcycle gang causing trouble in town, and a disturbed neighbor setting fires, Jack realizes it isn’t just Pete who needs saving. Set during a single, tumultuous summer, this beautifully told tale is a heartwarming tribute to innocence, first love, and the unbreakable bond of brotherhood.', price='10.99', category='literary-fiction', author='Bill Rivers', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/71Ip8PV+51L.jpg')

    # <NavLink to={'books/45'}><img id='honey' src='https://images-na.ssl-images-amazon.com/images/I/41J43ERHtLL._SX321_BO1,204,203,200_.jpg'></img></NavLink>
    # <NavLink to={'books/46'}><img id='connection' src='https://images-na.ssl-images-amazon.com/images/I/41zLDmfXMIL._SX311_BO1,204,203,200_.jpg'></img></NavLink>
    # <NavLink to={'books/47'}><img id='odyssey' src='https://images-na.ssl-images-amazon.com/images/I/51S8fUZ6nfL._SX331_BO1,204,203,200_.jpg'></img></NavLink>
    # <NavLink to={'books/48'}><img id='flowers' src='https://images-na.ssl-images-amazon.com/images/I/416ZrnNLj6L._SX321_BO1,204,203,200_.jpg'></img></NavLink>

    db.session.add(GAMEOFTHRONES)
    db.session.add(THENAMEOFTHEWIND)
    db.session.add(THELORDOFTHERINGS)
    db.session.add(COLOROFMAGIC)
    db.session.add(EIGHTYFOUR)
    db.session.add(FAHRENHEIT)
    db.session.add(BRAVENEWWORLD)
    db.session.add(DUNE)
    db.session.add(IMPERIAL)
    db.session.add(MOONSTONE)
    db.session.add(SCARLET)
    db.session.add(MURDER)
    db.session.add(POISONED)
    db.session.add(DONQUIXOTE)
    db.session.add(THREEMUSKETEERS)
    db.session.add(TREASURE)
    db.session.add(MOBYDICK)
    db.session.add(ELONMUSK)
    db.session.add(STEVEJOBS)
    db.session.add(EINSTEIN)
    db.session.add(EDISON)
    db.session.add(DOAWK)
    db.session.add(TREEHOUSE)
    db.session.add(CHARLOTTE)
    db.session.add(HARRYPOTTER)
    db.session.add(THEWOK)
    db.session.add(HOMEFOOD)
    db.session.add(HALFBAKED)
    db.session.add(MASALA)
    db.session.add(HAUNTINGHILL)
    db.session.add(IT)
    db.session.add(EXORCIST)
    db.session.add(LEAVES)
    db.session.add(SEVENTEENSEVENTYSIX)
    db.session.add(CRUSADES)
    db.session.add(GUNSGERMSSTEEL)
    db.session.add(EUROPE)
    db.session.add(MOCKINGBIRD)
    db.session.add(GATSBY)
    db.session.add(CATCHER)
    db.session.add(ANIMALFARM)
    db.session.add(ONEPIECE)
    db.session.add(NARUTO)
    db.session.add(DRAGONBALLZ)
    db.session.add(DEATHNOTE)
    db.session.add(MILKHONEY)
    db.session.add(CHASESUN)
    db.session.add(HEALING)
    db.session.add(SUNFLOWERS)
    db.session.add(WHATSHEFOUND)
    db.session.add(REMINDERS)
    db.session.add(BEYOND)
    db.session.add(SUMMER)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_products():
    db.session.execute('TRUNCATE products RESTART IDENTITY CASCADE;')
    db.session.commit()
