from unicodedata import category
from app.models import db, Product


# Adds a demo user, you can add other users here if you want
def seed_products():
    GAMEOFTHRONES = Product(
        name='Game of Thrones', description='Winter is coming. Such is the stern motto of House Stark, the northernmost of the fiefdoms that owe allegiance to King Robert Baratheon in far-off Kings Landing. There Eddard Stark of Winterfell rules in Roberts name. There his family dwells in peace and comfort: his proud wife, Catelyn; his sons Robb, Brandon, and Rickon; his daughters Sansa and Arya; and his bastard son, Jon Snow. Far to the north, behind the towering Wall, lie savage Wildings and worse - unnatural things relegated to myth during the centuries-long summer, but proving all too real and all too deadly in the turning of the season. Yet a more immediate threat lurks to the south, where Jon Arryn, the Hand of the King, has died under mysterious circumstances. Now Robert is riding north to Winterfell, bringing his queen, the lovely but cold Cersei, his son, the cruel, vainglorious Prince Joffrey, and the queens brothers Jaime and Tyrion of the powerful and wealthy House Lannister - the first a swordsman without equal, the second a dwarf whose stunted stature belies a brilliant mind.', price='12.99', category='fantasy', author='George R.R. Martin', photourl='https://m.media-amazon.com/images/I/51rDpMtBm5L.jpg')
    THENAMEOFTHEWIND = Product(
        name='Name of the Wind', description='The Name of the Wind, also referred to as The Kingkiller Chronicle: Day One, is a heroic fantasy novel written by American author Patrick Rothfuss. It is the first book in the ongoing fantasy trilogy The Kingkiller Chronicle, followed by The Wise Mans Fear. It was published on March 27, 2007, by DAW Books.', price='9.89', category='fantasy', author='Patrick Rothfuss', photourl='https://images-na.ssl-images-amazon.com/images/I/91b8oNwaV1L.jpg')
    THELORDOFTHERINGS = Product(
        name='Lord of the Rings', description='Since it was first published in 1954, The Lord of the Rings has been a book people have treasured. Steeped in unrivaled magic and otherworldliness, Tolkien\'s sweeping fantasy and epic adventure has touched the hearts of young and old alike. More than 150 million copies of its many editions have been sold around the world, and occasional collectors’ editions become prized and valuable items of publishing. This one-volume, jacketed hardcover edition contains the complete text, fully corrected and reset, which is printed in red and black and features, for the very first time, thirty color illustrations, maps and sketches drawn by Tolkien himself as he composed this epic work. These include the pages from the Book of Mazarbul, marvelous facsimiles created by Tolkien to accompany the famous ‘Bridge of Khazad-dum’ chapter. Also appearing are two removable fold-out maps drawn by Christopher Tolkien revealing all the detail of Middle-earth. Sympathetically packaged to reflect the classic look of the first edition, this new edition of the bestselling hardback will prove irresistible to collectors and new fans alike.', price='10.99', category='fantasy', author='John Tolkien', photourl='https://images-na.ssl-images-amazon.com/images/I/71jLBXtWJWL.jpg')
    COLOROFMAGIC = Product(
        name='Color of Magic', description='The Colour of Magic & The Light Fantastic: This is how the Discworld began... In The Colour of Magic the failed wizard Rincewind burst upon the world and hasn\'t stopped running since. This was the book that started the phenomenally successful fantasy series. Here is the sapient pearwood Luggage, a mobile trunk which launders any clothes put in it and incidentally homicidally defends its owner. Here is Twoflower, an innocent tourist in a world of nightmares and fairy tales gone wrong. Here is Cohen the Barbarian, the world\'s oldest and greatest hero. Here is Death, not such a bad sort when you get to know him... They have adventures. It\'d take to long too explain. Just read it! First published in 1983, The Colour of Magic has been translated into thirty languages, and has sold over two million copies in Corgi editions alone. The Light Fantastic, published in 1986, follows closely behind, and of all the Discworld novels it is the only true sequel to an earlier work. This two-in-one volume was first published in 1999.', price='13.99', category='fantasy', author='Terry Pratchett', photourl='https://images-na.ssl-images-amazon.com/images/I/91u24IHWS8L.jpg')
    EIGHTYFOUR = Product(
        name='1984', description='“The Party told you to reject the evidence of your eyes and ears. It was their final, most essential command.” Winston Smith toes the Party line, rewriting history to satisfy the demands of the Ministry of Truth. With each lie he writes, Winston grows to hate the Party that seeks power for its own sake and persecutes those who dare to commit thoughtcrimes. But as he starts to think for himself, Winston can’t escape the fact that Big Brother is always watching...A startling and haunting novel, 1984 creates an imaginary world that is completely convincing from start to finish. No one can deny the novel’s hold on the imaginations of whole generations, or the power of its admonitions—a power that seems to grow, not lessen, with the passage of time.', price='14.99', category='sci-fi', author='George Orwell', photourl='https://images-na.ssl-images-amazon.com/images/I/71kxa1-0mfL.jpg')
    FAHRENHEIT = Product(
        name='Fahrenheit 451', description='Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But when he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known.', price='8.29', category='sci-fi', author='Ray Bradbury', photourl='https://www.arts.gov/sites/default/files/Fahrenheit%20451%20Cover.jpg')
    BRAVENEWWORLD = Product(
        name='Brave New World', description='Aldous Huxley\'s profoundly important classic of world literature, Brave New World is a searching vision of an unequal, technologically-advanced future where humans are genetically bred, socially indoctrinated, and pharmaceutically anesthetized to passively uphold an authoritarian ruling order–all at the cost of our freedom, full humanity, and perhaps also our souls. “A genius [who] who spent his life decrying the onward march of the Machine” (The New Yorker), Huxley was a man of incomparable talents: equally an artist, a spiritual seeker, and one of history’s keenest observers of human nature and civilization. Brave New World, his masterpiece, has enthralled and terrified millions of readers, and retains its urgent relevance to this day as both a warning to be heeded as we head into tomorrow and as thought-provoking, satisfying work of literature. Written in the shadow of the rise of fascism during the 1930s, Brave New World likewise speaks to a 21st-century world dominated by mass-entertainment, technology, medicine and pharmaceuticals, the arts of persuasion, and the hidden influence of elites.', price='10.99', category='sci-fi', author='Aldous Huxley', photourl='https://images-na.ssl-images-amazon.com/images/I/81zE42gT3xL.jpg')
    DUNE = Product(
        name='Dune', description='Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, who would become the mysterious man known as Maud\'dib. He would avenge the traitorous plot against his noble family - and would bring to fruition humankind\'s most ancient and unattainable dream. A stunning blend of adventure and mysticism, environmentalism and politics, Dune won the first Nebula Award, shared the Hugo Award, and formed the basis of what is undoubtedly the grandest epic in science fiction.Frank Herbert\'s death in 1986 was a tragic loss, yet the astounding legacy of his visionary fiction will live forever.', price='10.99', category='sci-fi', author='Frank Herbert', photourl='https://images-na.ssl-images-amazon.com/images/I/81ym3QUd3KL.jpg')
    MOONSTONE = Product(
        name='Moonstone', description='The Moonstone by Wilkie Collins. Introduction and Notes by David Blair, Rutherford College, University of Kent The Moonstone, a priceless Indian diamond which had been brought to England as spoils of war, is given to Rachel Verrinder on her eighteenth birthday. That very night, the stone is stolen. Suspicion then falls on a hunchbacked housemaid, on Rachel\'s cousin Franklin Blake, on a troupe of mysterious Indian jugglers, and on Rachel herself. The phlegmatic Sergeant Cuff is called in, and with the help of Betteredge, the Robinson Crusoe-reading loquacious steward, the mystery of the missing stone is ingeniously solved.', price='5.99', category='mystery', author='Wilkie Collins', photourl='https://images-na.ssl-images-amazon.com/images/I/41sxrEkyqdL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg')
    SCARLET = Product(
        name='Scarlet', description='Arthur Conan Doyle’s first ‘Sherlock Homes’ novel introduces the talented detective Holmes to his loyal partner in investigation, Dr. John Watson. A Study in Scarlet is the first of four full length Sherlock Holmes novels written by Arthur Conan Doyle. The novel begins with a war-wounded Watson being introduced to Holmes by a common friend, when looking for a place to stay. Initially wary of Holmes’s eccentricities, Watson gradually starts appreciating Sherlock’s knowledge and exceptional abilities of logical deduction.', price='9.99', category='mystery', author='Marissa Meyer', photourl='https://www.publicbookshelf.com/images/AStudyInScarlet423x630.jpg')
    MURDER = Product(
        name='Murder on the Orient Express', description='“Just after midnight, the famous Orient Express is stopped in its tracks by a snowdrift. By morning, the millionaire Samuel Edward Ratchett lies dead in his compartment, stabbed a dozen times, his door locked from the inside. Without a shred of doubt, one of his fellow passengers is the murderer. Isolated by the storm, detective Hercule Poirot must find the killer among a dozen of the dead man’s enemies, before the murderer decides to strike again. “What more . . . can a mystery addict desire?” — New York Times', price='8.49', category='mystery', author='Agatha Christie', photourl='https://m.media-amazon.com/images/P/0062073494.01._SCLZZZZZZZ_SX500_.jpg')
    POISONED = Product(
        name='The Poisoned Chocolates Case', description='“Graham and Joan Bendix have apparently succeeded in making that eighth wonder of the modern world, a happy marriage. But into the middle of it drops a box of chocolates. Joan Bendix is killed by a poisoned box of liqueur chocolates that cannot have been intended for her. The police investigation reaches a dead end. Chief Inspector Moresby calls on Roger Sheringham and his Crimes Circle - six amateur but intrepid detectives - to consider the case. The evidence is laid before them and they take turns to offer a solution. Each is more convincing than the last, slowly filling in the pieces of the puzzle, until the dazzling conclusion.” — New York Times', price='32.50', category='mystery', author='Anthony Berkeley', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/51T5N0KOoJL._SX320_BO1,204,203,200_.jpg')
    DONQUIXOTE = Product(
        name='Don Quixote', description='“Don Quixote has become so entranced reading tales of chivalry that he decides to turn knight errant himself. In the company of his faithful squire, Sancho Panza, these exploits blossom in all sorts of wonderful ways. While Quixote\'s fancy often leads him astray—he tilts at windmills, imagining them to be giants—Sancho acquires cunning and a certain sagacity. Sane madman and wise fool, they roam the world together-and together they have haunted readers\' imaginations for nearly four hundred years. With its experimental form and literary playfulness, Don Quixote has been generally recognized as the first modern novel. This Penguin Classics edition, with its beautiful new cover design, includes John Rutherford\'s masterly translation, which does full justice to the energy and wit of Cervantes\'s prose, as well as a brilliant critical introduction by Roberto Gonzalez Echevarriá.', price='12.99', category='action', author='Miguel de Cervantes', photourl='https://m.media-amazon.com/images/P/0142437239.01._SCLZZZZZZZ_SX500_.jpg')
    THREEMUSKETEERS = Product(
        name='The Three Musketeers', description='First serialized between March and July of 1844, Alexandre Dumas’s “The Three Musketeers” is one of the author’s most famous works, the opening installment in the “d\'Artagnan Romances.” A timeless tale of adventure, romance, intrigue, and revenge, it is the captivating story of d’Artagnan, a young man of Gascony, who is determined to become a Musketeer of the Royal Guard. Through his wit and skill with a sword, he befriends the other Musketeers, Athos, Porthos, and Aramis. Together they must foil the nefarious plotting of Cardinal Richelieu against the King and Queen, despite his appearance as an ally. The Musketeers must also overcome the villainous machinations of Milady de Winter, whose lethal criminality threatens those in power and the love of d’Artagnan for Constance Bonacieux. Dumas’s classic story has enthralled readers with its fast-paced action, endearing characters, and romantic ideals ever since its original publication. The camaraderie of the Musketeers has been forever immortalized by their famous motto “one for all, all for one.” This edition is printed on premium acid-free paper and includes an introduction by J. Walker McSpadden.', price='14.99', category='action', author='Alexandre Dumas', photourl='https://m.media-amazon.com/images/P/1420953788.01._SCLZZZZZZZ_SX500_.jpg')
    TREASURE = Product(
        name='Treasure Island', description='“**Published by Cricket House Books ISBN 9781625009975** “Treasure Island” is an adventure novel by the Scottish author Robert Louis Stevenson, published in 1883. It has had significant influence on the common perception of pirates. The novel is also a coming-of-age story, as the young protagonist, Jim, faces moral lessons and navigates dangerous situations.', price='9.99', category='action', author='Robert Louis Stevenson', photourl='https://m.media-amazon.com/images/P/1625009976.01._SCLZZZZZZZ_SX500_.jpg')
    MOBYDICK = Product(
        name='Moby Dick', description='“A masterpiece of storytelling, this epic saga pits Ahab, a brooding and fantastical sea captain, against the great white whale that crippled him. In telling the tale of Ahab\'s passion for revenge and the fateful voyage that ensued, Melville produced far more than the narrative of a hair-raising journey; Moby-Dick is a tale for the ages that sounds the deepest depths of the human soul.Interspersed with graphic sketches of life aboard a whaling vessel, and a wealth of information on whales and 19th-century whaling, Melville\'s greatest work presents an imaginative and thrilling picture of life at sea, as well as a portrait of heroic determination. The author\'s keen powers of observation and firsthand knowledge of shipboard life (he served aboard a whaler himself) were key ingredients in crafting a maritime story that dramatically examines the conflict between man and nature. "A valuable addition to the literature of the day," said American journalist Horace Greeley on the publication of Moby-Dick in 1851 — a classic piece of understatement about a literary classic now considered by many as "the great American novel." Read and pondered by generations, the novel remains an unsurpassed account of the ultimate human struggle against the indifference of nature and the awful power of fate. Much of Moby Dick was inspired by the 1821 work Narratives of the Wreck of the Whale-Ship Essex, which in turn inspired the 2015 movie In the Heart of the Sea, directed by Ron Howard and starring Chris Hemsworth.', price='5.99', category='action', author='Herman Melville', photourl='https://m.media-amazon.com/images/P/0486432157.01._SCLZZZZZZZ_SX500_.jpg')
    ELONMUSK = Product(
        name='Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future', description='New York Times and International Bestseller Named One of the Best Books of the Year by The Wall Street Journal, NPR, Audible and Amazon More than 2 million copies sold In the spirit of Steve Jobs and Moneyball, Elon Musk is both an illuminating and authorized look at the extraordinary life of one of Silicon Valley\'s most exciting, unpredictable, and ambitious entrepreneurs--a real-life Tony Stark--and a fascinating exploration of the renewal of American invention and its new "makers." Elon Musk spotlights the technology and vision of Elon Musk, the renowned entrepreneur and innovator behind SpaceX, Tesla, and SolarCity, who sold one of his Internet companies, PayPal, for $1.5 billion. Ashlee Vance captures the full spectacle and arc of the genius\'s life and work, from his tumultuous upbringing in South Africa and flight to the United States to his dramatic technical innovations and entrepreneurial pursuits. Vance uses Musk\'s story to explore one of the pressing questions of our age: can the nation of inventors and creators who led the modern world for a century still compete in an age of fierce global competition? He argues that Musk--one of the most unusual and striking figures in American business history--is a contemporary, visionary amalgam of legendary inventors and industrialists including Thomas Edison, Henry Ford, Howard Hughes, and Steve Jobs. More than any other entrepreneur today, Musk has dedicated his energies and his own vast fortune to inventing a future that is as rich and far-reaching as the visionaries of the golden age of science-fiction fantasy. Thorough and insightful, Elon Musk brings to life a technology industry that is rapidly and dramatically changing by examining the life of one of its most powerful and influential titans.', price='13.39', category='biography', author='Ashley Vance', photourl='https://m.media-amazon.com/images/P/006230125X.01._SCLZZZZZZZ_SX500_.jpg')
    STEVEJOBS = Product(
        name='Steve Jobs', description='“Based on more than 40 interviews with Jobs conducted over two years - as well as interviews with more than a hundred family members, friends, adversaries, competitors, and colleagues - Walter Isaacson has written a riveting story of the roller-coaster life and searingly intense personality of a creative entrepreneur whose passion for perfection and ferocious drive revolutionized six industries: personal computers, animated movies, music, phones, tablet computing, and digital publishing. At a time when America is seeking ways to sustain its innovative edge, and when societies around the world are trying to build digital-age economies, Jobs stands as the ultimate icon of inventiveness and applied imagination. He knew that the best way to create value in the 21st century was to connect creativity with technology. He built a company where leaps of the imagination were combined with remarkable feats of engineering. Although Jobs cooperated with this book, he asked for no control over what was written. He put nothing off-limits. He encouraged the people he knew to speak honestly. And Jobs speaks candidly, sometimes brutally so, about the people he worked with and competed against. His friends, foes, and colleagues provide an unvarnished view of the passions, perfectionism, obsessions, artistry, devilry, and compulsion for control that shaped his approach to business and the innovative products that resulted. Driven by demons, Jobs could drive those around him to fury and despair. But his personality and products were interrelated, just as Apple\'s hardware and software tended to be, as if part of an integrated system. His tale is instructive and cautionary, filled with lessons about innovation, character, leadership, and values.', price='15.50', category='biogrphy', author='Walter Isaacson', photourl='https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51S2iJN3DYL.jpg')
    EINSTEIN = Product(
        name='Einstein: His Life and Universe', description='How did Einstein\'s mind work? What made him a genius? Isaacson\'s biography shows how his scientific imagination sprang from the rebellious nature of his personality. His fascinating story is a testament to the connection between creativity and freedom. Based on the newly released personal letters of Albert Einstein, Walter Isaacson explores how an imaginative, impertinent patent clerk, a struggling father in a difficult marriage who couldn\'t get a teaching job or a doctorate, became the mind reader of the creator of the cosmos, the locksmith of the mysteries of the atom and the universe. His success came from questioning conventional wisdom and marveling at mysteries that struck others as mundane. This led him to embrace a morality and politics based on respect for free minds, free spirits, and free individuals. These traits are just as vital for this new century of globalization, in which our success will depend on our creativity, as they were for the beginning of the last century, when Einstein helped usher in the modern age.', price='12.46', category='biography', author='Walter Isaacson', photourl='https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51VEeZWAo-L.jpg')
    EDISON = Product(
        name='Thomas Edison: The One Who Changed The World', description='There are a lot more to the story than just the light bulb, and there is a lot more to the invention of the light bulb than just Thomas Edison. One thing is for sure that he is still remembered as one of the greatest inventors of all time, and perhaps the greatest that America has ever produced. In truth, Edison was a man who invented a lot of things while bringing about incredible advancements in many other things. With the stock ticker, the telegraph, the light bulb, and motion picture, he may not have invented them, but he improved on them beyond any recognition. They would not be the technologies they were today without Edison’s great mind working on them.', price='10.99', category='biography', author='THE HISTORY HOUR', photourl='https://m.media-amazon.com/images/P/171816095X.01._SCLZZZZZZZ_SX500_.jpg')
    DOAWK = Product(
        name='Diary of a Wimpy Kid', description='It’s a new school year, and Greg Heffley finds himself thrust into middle school, where undersized weaklings share the hallways with kids who are taller, meaner, and already shaving. The hazards of growing up before you’re ready are uniquely revealed through words and drawings as Greg records them in his diary. In book one of this debut series, Greg is happy to have Rowley, his sidekick, along for the ride. But when Rowley’s star starts to rise, Greg tries to use his best friend’s newfound popularity to his own advantage, kicking off a chain of events that will test their friendship in hilarious fashion. Author/illustrator Jeff Kinney recalls the growing pains of school life and introduces a new kind of hero who epitomizes the challenges of being a kid. As Greg says in his diary, “Just don’t expect me to be all ‘Dear Diary’ this and ‘Dear Diary’ that.” Luckily for us, what Greg Heffley says he won’t do and what he actually does are two very different things. Since its launch in May 2004 on Funbrain.com, the Web version of Diary of a Wimpy Kid has been viewed by 20 million unique online readers. This year, it is averaging 70,000 readers a day. F&P level: T', price='9.48', category='childrens', author='Jeff Kinney', photourl='https://m.media-amazon.com/images/P/0810993139.01._SCLZZZZZZZ_SX500_.jpg')
    TREEHOUSE = Product(
        name='Magic Tree House: Pirates Past Noon', description='The #1 bestselling chapter book series of all time celebrates 25 years with new covers and a new, easy-to-use numbering system! It\'s a treasure trove of trouble! Jack and Annie are in for a high-seas adventure when the Magic Tree House whisks them back to the days of deserted islands, secret maps—and ruthless pirates! Will they discover a buried treasure? Or will they be forced to walk the plank?', price='3.83', category='childrens', author='Mary Pope Osbourne', photourl='https://m.media-amazon.com/images/P/0679824251.01._SCLZZZZZZZ_SX500_.jpg')
    CHARLOTTE = Product(
        name='Charlotte\'s Web', description='Some Pig. Humble. Radiant. These are the words in Charlotte\'s Web, high up in Zuckerman\'s barn. Charlotte\'s spiderweb tells of her feelings for a little pig named Wilbur, who simply wants a friend. They also express the love of a girl named Fern, who saved Wilbur\'s life when he was born the runt of his litter. E. B. White\'s Newbery Honor Book is a tender novel of friendship, love, life, and death that will continue to be enjoyed by generations to come. It contains illustrations by Garth Williams, the acclaimed illustrator of E. B. White\'s Stuart Little and Laura Ingalls Wilder\'s Little House series, among many other books. Whether enjoyed in the classroom or for homeschooling or independent reading, Charlotte\'s Web is a proven favorite.', price='5.47', category='childrens', author='E.B. White', photourl='https://m.media-amazon.com/images/P/0064400557.01._SCLZZZZZZZ_SX500_.jpg')
    HARRYPOTTER = Product(
        name='Harry Potter and the Sorcerer\'s Stone', description='Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry\'s eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!  — New York Times', price='9.99', category='childrens', author='J.K. Rowling', photourl='https://m.media-amazon.com/images/W/WEBP_402378-T2/images/I/51Ppi-8kISL.jpg')
    THEWOK = Product(
        name='The Wok: Recipes and Techniques', description='“J. Kenji López-Alt’s debut cookbook, The Food Lab, revolutionized home cooking, selling more than half a million copies with its science-based approach to everyday foods. And for fast, fresh cooking for his family, there’s one pan López-Alt reaches for more than any other: the wok. Whether stir-frying, deep frying, steaming, simmering, or braising, the wok is the most versatile pan in the kitchen. Once you master the basics―the mechanics of a stir-fry, and how to get smoky wok hei at home―you’re ready to cook home-style and restaurant-style dishes from across Asia and the United States, including Kung Pao Chicken, Pad Thai, and San Francisco–Style Garlic Noodles. López-Alt also breaks down the science behind beloved Beef Chow Fun, fried rice, dumplings, tempura vegetables or seafood, and dashi-simmered dishes. Featuring more than 200 recipes―including simple no-cook sides―explanations of knife skills and how to stock a pantry, and more than 1,000 color photographs, The Wok provides endless ideas for brightening up dinner.', price='29.69', category='cookbooks', author='J. Kenji López-Alt ', photourl='https://m.media-amazon.com/images/P/0393541215.01._SCLZZZZZZZ_SX500_.jpg')
    HOMEFOOD = Product(
        name='Home Food: 100 Recipes to Comfort and Connect', description='In her most personal book yet, Olia Hercules distills a lifetime of kitchen curiosity into her 100 most loved recipes. She draws on her broad influences: her childhood in Eastern Europe; her years in Cyprus and Italy; her simple, plant-centric family meals at home in London; and the special festive recipes she has gleaned along the way. All these seemingly diverse recipes are centered in comfort and connection. These are recipes that have been hand written, handed down, and shared among friends: “They are nostalgic like the potatoes of my childhood, they share trade secrets like Bisque-style red mullet pasta, they interweave every day like Joe’s beet, feta, and potatoes, and they make everything ok like Life-giving rhubarb cake. The foods we choose to cook time and again are part of what makes us, and when we share those recipes, we give a little of ourselves.” In this book Olia gives us her food story through her very favorite recipes.', price='31.50', category='cookbooks', author='Olia Hercules', photourl='https://images-na.ssl-images-amazon.com/images/W/WEBP_402378-T2/images/I/515umZ9nRbL._SX391_BO1,204,203,200_.jpg')
    HALFBAKED = Product(
        name='Half Baked Harvest Every Day: Recipes for Balanced, Flexible, Feel-Good Meals', description='The millions of fans of the Half Baked Harvest blog and bestselling books have fallen in love with Tieghan Gerard’s recipes for their wholesome decadence, unfussy approach, and smart twists on comforting favorites. Written and photographed in the stunning mountains of Colorado, inspired by her big, unique family, and focused on what you’ll want to eat day-in-day-out, Half Baked Harvest Every Day delivers more than 120 all-new recipes that will feed your body and soul. For Tieghan, feel-good food isn’t about restrictive eating. It’s about enjoying real food with lots of flavor, and the satisfaction of sharing it with those you love. Finding balance is about giving your body and your cravings what they need . . . whether that’s a light, vegetable-packed dish or a big ole plate of something comforting. In this collection, there are plenty of plant-forward favorites, like Chipotle Cheddar Corn Chowder and Spinach and Pesto–Stuffed Butternut Squash. Tieghan also shares flavor-packed family go-tos, like Pizza Pasta with Pepperoni Bread Crumbs, Crispy Carnitas Taquitos, and Spicy Pretzel Chicken Fingers with Hot Honey. And to keep a smile on everyone’s face, you’ll find luscious desserts, like Chocolate Olive Oil Cake and a Lemon Tart with Vanilla Sugar, made with a focus on wholesome, minimally processed ingredients. Whether it’s breakfast, lunch, snack time, dinner, or dessert . . . this book has tried-and-true recipes that will make you feel good about sharing them at your table.', price='18.49', category='cookbooks', author='Tieghan Gerard', photourl='https://assets.wsimgs.com/wsimgs/ab/images/dp/wcm/202221/0044/img87o.jpg')
    MASALA = Product(
        name='Masala: Recipes from India, the Land of Spices', description='Award-winning chef Anita Jaisinghani of Pondicheri restaurant in Houston, Texas, shows just how easy, delicious, and healthy Indian food can be in this stunning and accessible debut cookbook. Born and raised in Gujarat, India, Anita’s approach to cooking is simple: Following the tenets of ancient Ayurveda, food is seasonal, texture and color are celebrated, and spices are used to enhance, not overwhelm. As the star of Indian cuisine, spices are used from morning to night, in simple infusions, such as cinnamon water for a warming start the day, while cilantro and mint add a cooling balance to a fiery grilled corn salad, and cardamom lends an aromatic sweetness to mango rice pudding. Masala will teach you to think like an Indian chef, revealing the wisdom and techniques to cooking with fresh whole spices: identifying warming versus cooling, what order they should be used, how to temper in hot oil, and much more. Drawing inspiration from every corner of India, these recipes include fermented dosas, sweet and savory chutneys, fragrant chicken, fish, and pork curries, samosas, pakoras, and naans, and pay homage to one of the oldest and most diverse cuisines on the planet. Expect to be wowed with new flavors and combinations, such as Saffron Citrus Pilaf, Coconut Lassi, Jackfruit Masala, Vindaloo Ribs, Avocado Mushroom Chilla, and Smoked Eggplant Raita.', price='33.12', category='cookbooks', author='Anita Jaisinghani', photourl='https://images-na.ssl-images-amazon.com/images/I/A1xK8xq8+-L.jpg')

    db.session.add(GAMEOFTHRONES)
    db.session.add(THENAMEOFTHEWIND)
    db.session.add(THELORDOFTHERINGS)
    db.session.add(COLOROFMAGIC)
    db.session.add(EIGHTYFOUR)
    db.session.add(FAHRENHEIT)
    db.session.add(BRAVENEWWORLD)
    db.session.add(DUNE)
    db.session.add(MOONSTONE)
    db.session.add(SCARLET)
    db.session.add(MURDER)
    db.session.add(POISONED)
    db.session.add(DONQUIXOTE)
    db.session.add(THREEMUSKETEERS)
    db.session.add(TREASURE)
    db.session.add(MOBYDICK)
    db.session.add(ELONMUSK)
    db.session.add(STEVEJOBS)
    db.session.add(EINSTEIN)
    db.session.add(EDISON)
    db.session.add(DOAWK)
    db.session.add(TREEHOUSE)
    db.session.add(CHARLOTTE)
    db.session.add(HARRYPOTTER)
    db.session.add(THEWOK)
    db.session.add(HOMEFOOD)
    db.session.add(HALFBAKED)
    db.session.add(MASALA)

    db.session.commit()


# Uses a raw SQL query to TRUNCATE the users table.
# SQLAlchemy doesn't have a built in function to do this
# TRUNCATE Removes all the data from the table, and RESET IDENTITY
# resets the auto incrementing primary key, CASCADE deletes any
# dependent entities
def undo_products():
    db.session.execute('TRUNCATE products RESTART IDENTITY CASCADE;')
    db.session.commit()
